# Generated by Django 3.1.4 on 2021-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0138_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sku_simple',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
