# Generated by Django 3.1.4 on 2021-01-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('product', '0139_productvariant_sku_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vendors.vendor'),
        ),
    ]
