# Generated by Django 3.1.4 on 2021-01-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0140_productvariant_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='vendor',
        ),
    ]
