# Generated by Django 3.1.4 on 2021-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0141_remove_productvariant_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_simple',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
