# Generated by Django 3.1.4 on 2021-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0142_product_id_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_simple',
            field=models.IntegerField(null=True),
        ),
    ]
