# Generated by Django 3.1.4 on 2021-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0144_auto_20210113_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
    ]
