# Generated by Django 3.1.4 on 2021-05-26 21:49

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0146_auto_20210521_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='AR', max_length=3)),
                ('province', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('lat', models.CharField(blank=True, max_length=20)),
                ('lon', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PastExperienceGeneralImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='vendors')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('alt', models.CharField(blank=True, default='foto de experiencia pasada', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PastExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_short', models.CharField(max_length=20)),
                ('description_long', models.CharField(blank=True, max_length=1000)),
                ('year_performed', models.IntegerField()),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.experiencelocation')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='past_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.pastexperience'),
        ),
        migrations.CreateModel(
            name='PastExperienceImage',
            fields=[
                ('pastexperiencegeneralimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.pastexperiencegeneralimage')),
                ('position', models.IntegerField()),
                ('past_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_experience_images', to='product.pastexperience')),
            ],
            bases=('product.pastexperiencegeneralimage',),
        ),
    ]
