# Generated by Django 3.1.4 on 2021-05-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0147_auto_20210526_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='past_experience',
        ),
        migrations.AddField(
            model_name='pastexperience',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
