# Generated by Django 3.1.4 on 2021-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0150_auto_20210527_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastexperience',
            name='in_construirte',
            field=models.BooleanField(default=False),
        ),
    ]
