# Generated by Django 3.1.4 on 2021-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_pastexperience_in_construirte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexperience',
            name='description_short',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pastexperience',
            name='year_performed',
            field=models.IntegerField(blank=True),
        ),
    ]
