# Generated by Django 3.1.4 on 2021-05-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0152_auto_20210529_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexperience',
            name='year_performed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
