# Generated by Django 3.1.4 on 2021-06-05 20:18

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0154_auto_20210531_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexperiencegeneralimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='experiences'),
        ),
    ]
