# Generated by Django 3.1.4 on 2021-04-11 20:18

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20210411_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='main_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='vendor-main'),
        ),
    ]
