# Generated by Django 3.1.4 on 2021-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='billing',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bussiness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='founding_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='open_hours',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='vendor',
            name='quality_norms',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_employess',
            field=models.IntegerField(null=True),
        ),
    ]
