# Generated by Django 3.1.4 on 2021-04-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20210423_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website_url',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('roles', models.CharField(blank=True, choices=[('available', 'sales'), ('borrowed', 'purchasing'), ('any', 'indefinite')], max_length=30)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
        ),
    ]
