# Generated by Django 3.1.4 on 2021-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20210423_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcontact',
            name='roles',
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='role',
            field=models.CharField(blank=True, choices=[('sales', 'sales'), ('purchasing', 'purchasing'), ('indefinite', 'any')], max_length=30),
        ),
    ]
