# Generated by Django 3.1.4 on 2021-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_auto_20210423_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontact',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'none'), ('sales', 'sales'), ('purchasing', 'purchasing'), ('indefinite', 'any')], max_length=30),
        ),
    ]
