# Generated by Django 3.1.4 on 2021-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_auto_20210505_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlocation',
            name='lat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='lon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
