# Generated by Django 3.1.4 on 2021-05-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorimage',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
