# Generated by Django 3.1.4 on 2021-05-15 17:31

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_vendorimage_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorGeneralImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='vendors')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('alt', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AlterModelOptions(
            name='vendorimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='vendorimage',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='vendorimage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendorimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendorimage',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='vendorimage',
            name='sort_order',
        ),
        migrations.CreateModel(
            name='VendorMainImage',
            fields=[
                ('vendorgeneralimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='vendors.vendorgeneralimage')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='main_image', serialize=False, to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
            bases=('vendors.vendorgeneralimage',),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='vendorgeneralimage_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.vendorgeneralimage'),
            preserve_default=False,
        ),
    ]
