# Generated by Django 3.1.4 on 2021-05-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_auto_20210515_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorserviceimage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='vendors.vendor'),
        ),
    ]
