# Generated by Django 3.1.4 on 2021-05-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_auto_20210515_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontact',
            name='role',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('salez', 'saless'), ('purchasing', 'purchasing'), ('indefinite', 'any')], max_length=30),
        ),
    ]
