# Generated by Django 3.1.4 on 2021-05-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_auto_20210517_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorgeneralimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendorserviceimage',
            options={'ordering': ('sort_order', 'pk')},
        ),
        migrations.RemoveField(
            model_name='vendorgeneralimage',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='vendorserviceimage',
            name='sort_order',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendormainimage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='vendormainimage',
            name='vendorgeneralimage_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.vendorgeneralimage'),
        ),
    ]
