# Generated by Django 3.1.4 on 2021-06-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_vendorlocation_full_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('TW', 'Twitter')], max_length=3)),
                ('user_string', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
