# Generated by Django 3.1.4 on 2021-06-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
