# Generated by Django 3.1.4 on 2020-12-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='vendors.vendor'),
        ),
    ]
