# Generated by Django 3.1.4 on 2021-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_user_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_construirte_admin',
            field=models.BooleanField(default=False),
        ),
    ]
