# Generated by Django 3.1.4 on 2021-03-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_user_is_construirte_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_construirte_admin',
        ),
    ]
