# Generated by Django 3.1.4 on 2021-05-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_remove_user_is_construirte_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_identification',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('pasaporte', 'pasaporte')], max_length=30),
        ),
    ]
