# Generated by Django 3.1.4 on 2021-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20210504_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_identification',
            field=models.CharField(blank=True, choices=[('', 'none'), ('DNI', 'DNI'), ('pasaporte', 'pasaporte')], max_length=30),
        ),
    ]
