# Generated by Django 3.1.4 on 2021-05-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20210504_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_identification',
            field=models.CharField(blank=True, choices=[('', 'none'), ('DNI', 'DNI'), ('pasaporte', 'pasaporte')], default=None, max_length=30, null=True),
        ),
    ]
