# Generated by Django 3.1.4 on 2021-05-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20210505_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_identification',
        ),
    ]
