# Generated by Django 3.1.4 on 2021-12-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_user_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='types_of_users',
            field=models.CharField(choices=[('CONSUMIDOR_FINAL', 'Consumidor_final'), ('TIENDAS_MINORISTAS', 'Tiendas_minoristas'), ('MAYORISTAS/DISTRIBUIDOR', 'Mayoristas/Distribuidor'), ('CORPORATIVOS', 'Corporativos'), ('PRESTADOR_DE_SERVICIOS', 'Prestador_de_servicios')], default='CONSUMIDOR_FINAL', max_length=40),
        ),
    ]
