# Generated by Django 3.1.4 on 2021-08-20 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0155_auto_20210605_2018'),
        ('vendors', '0027_vendoravatarimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=400)),
                ('stage', models.IntegerField(default=0)),
                ('vendor_rejected', models.BooleanField(default=False)),
                ('accepted_but_not_finished', models.BooleanField(default=False)),
                ('user_reviewed', models.BooleanField(default=False)),
                ('vendor_reviewed', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.baseproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
