# Generated by Django 3.1.4 on 2021-09-03 21:36

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorContractReviewGeneralImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='services')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('alt', models.CharField(blank=True, default='foto de review del prestador de servicio', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VendorContractReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concreted', models.BooleanField(default=False)),
                ('motive', models.CharField(choices=[(1, 'Cliente no disponible'), (2, 'Prestador no se presenta'), (3, 'Trabajo no realizable'), (4, 'Otro')], default=4, max_length=40)),
                ('other_motive', models.CharField(default='No completa', max_length=300)),
                ('title', models.CharField(default='No completa', max_length=300)),
                ('long_review', models.CharField(default='No completa', max_length=1000)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecontract')),
            ],
        ),
        migrations.CreateModel(
            name='VendorContractReviewImage',
            fields=[
                ('vendorcontractreviewgeneralimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.vendorcontractreviewgeneralimage')),
                ('position', models.IntegerField()),
                ('vendor_contract_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contract_review_images', to='service.vendorcontractreview')),
            ],
            bases=('service.vendorcontractreviewgeneralimage',),
        ),
    ]
