# Generated by Django 3.1.4 on 2021-10-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_vendorcontractreview_vendorcontractreviewgeneralimage_vendorcontractreviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcontractreview',
            name='currency',
            field=models.CharField(default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='vendorcontractreview',
            name='job_price_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
