# Generated by Django 3.1.4 on 2021-12-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20211126_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontractreview',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contract_reviews', to='service.servicecontract'),
        ),
    ]
